### ISSUE TITLE
Traits download has not been updated for several months

### ISSUE THREAD

**Issue by ljwh2** [EBISPOT/goci#1317]
The traits download does not seem to have been update for several months. A download from 1st March is identical to the 5th May one, and several EFOs that have been updated in the UI have the old version in the download file. 

Example, https://www.ebi.ac.uk/gwas/efotraits/EFO_0022597 does not appear in the file, but "aging" appears with uri http://purl.obolibrary.org/obo/GO_0007568 which was obsoleted recently.

**Comment by Santhi1901** [comment]
the following terms added in 2024 are also not in the downloaded file:
age of onset of diverticulitis: http://purl.obolibrary.org/obo/OBA_2050355
placenta mass: http://purl.obolibrary.org/obo/OBA_VT0004257
level of endocrine disruptor in urine: http://purl.obolibrary.org/obo/OBA_2050419

**Comment by ala-ebi** [comment]
* mail server was causing issues, switched to hx-smtp instead of outgoing
* no patch for corrupt EFO release, switched to using old version https://github.com/EBISPOT/efo/releases/download/v3.66.0/efo.owl
* both the above changes are under {data_dir}/prod/config/application.properties
* jar file was previously SCP'd from an old version causing flyway errors, redeployed

**Comment by ala-ebi** [comment]
should be fixed in next DR

**Comment by sprintell** [comment]
Was running on garfield, moved to codon and that resolved the SMTP connectivity issues, changed the URI to Hinxton SMTP, ...

The version on teh cluster was an old one, a new deployment was done to resolve this, ...

**Comment by eks-ebi** [comment]
confirmed that the "aging" term is now correct and up to date

**Comment by eks-ebi** [comment]
other recently-added traits are also there in the updated spreadsheet, so I think this is done

**Comment by eks-ebi** [comment]
@Santhi1901 the only trait I still can't find in the spreadsheet is "placenta mass" - but this trait also looks broken in the Search UI: https://wwwdev.ebi.ac.uk/gwas/efotraits/OBA_VT0004257. Any idea what could be going on there?

**Comment by Santhi1901** [comment]
The paper is published with this EFO, but in the UI the term is missing.

I think the term is still not imported to EFO. This is the EFO ticket for this trait: https://github.com/EBISPOT/efo/issues/2116
